export const GET_SERVER_STATE = "GET_SERVER_STATE";
export const CLEAR_SERVER_STATE = "CLEAR_SERVER_STATE";
export const AUTH_ERROR = "AUTH_ERROR";

/* ADMIN */
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGINFAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_LOADED = "USER_PROFILE_LOADED";
export const USER_PROFILE_LOADING_FAIL = "USER_PROFILE_LOADING_FAIL";

export const MSGS_LOADING = "MSGS_LOADING";
export const MSGS_LOADING_SUCCESS = "MSGS_LOADING_SUCCESS";
export const MSGS_LOADING_FAIL = "MSGS_LOADING_FAIL";
